# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_window_ui.ui'
##
## Created by: Qt User Interface Compiler version 5.15.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import (QCoreApplication, QDate, QDateTime, QMetaObject,
    QObject, QPoint, QRect, QSize, QTime, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QKeySequence, QLinearGradient, QPalette, QPainter,
    QPixmap, QRadialGradient)
from PySide2.QtWidgets import *

from .media_player_widget import MediaPlayerWidget


class Ui_MainWindowUi(object):
    def setupUi(self, MainWindowUi):
        if not MainWindowUi.objectName():
            MainWindowUi.setObjectName(u"MainWindowUi")
        MainWindowUi.resize(920, 737)
        self.actionAddMusic = QAction(MainWindowUi)
        self.actionAddMusic.setObjectName(u"actionAddMusic")
        self.actionNewPlaylist = QAction(MainWindowUi)
        self.actionNewPlaylist.setObjectName(u"actionNewPlaylist")
        self.actionImportDatabase = QAction(MainWindowUi)
        self.actionImportDatabase.setObjectName(u"actionImportDatabase")
        self.actionExportDatabase = QAction(MainWindowUi)
        self.actionExportDatabase.setObjectName(u"actionExportDatabase")
        self.actionSettings = QAction(MainWindowUi)
        self.actionSettings.setObjectName(u"actionSettings")
        self.actionExportPlaylist = QAction(MainWindowUi)
        self.actionExportPlaylist.setObjectName(u"actionExportPlaylist")
        self.actionAddDirectory = QAction(MainWindowUi)
        self.actionAddDirectory.setObjectName(u"actionAddDirectory")
        self.actionImportPlaylist = QAction(MainWindowUi)
        self.actionImportPlaylist.setObjectName(u"actionImportPlaylist")
        self.actionNormal_1x = QAction(MainWindowUi)
        self.actionNormal_1x.setObjectName(u"actionNormal_1x")
        self.actionFaster = QAction(MainWindowUi)
        self.actionFaster.setObjectName(u"actionFaster")
        self.actionSlower = QAction(MainWindowUi)
        self.actionSlower.setObjectName(u"actionSlower")
        self.actionMush_Faster = QAction(MainWindowUi)
        self.actionMush_Faster.setObjectName(u"actionMush_Faster")
        self.actionMuch_Slower = QAction(MainWindowUi)
        self.actionMuch_Slower.setObjectName(u"actionMuch_Slower")
        self.actionJump_Forward = QAction(MainWindowUi)
        self.actionJump_Forward.setObjectName(u"actionJump_Forward")
        self.actionFump_Backward = QAction(MainWindowUi)
        self.actionFump_Backward.setObjectName(u"actionFump_Backward")
        self.actionJump_to_Specific_Time = QAction(MainWindowUi)
        self.actionJump_to_Specific_Time.setObjectName(u"actionJump_to_Specific_Time")
        self.actionPlay_Pause = QAction(MainWindowUi)
        self.actionPlay_Pause.setObjectName(u"actionPlay_Pause")
        self.actionStop = QAction(MainWindowUi)
        self.actionStop.setObjectName(u"actionStop")
        self.actionNext = QAction(MainWindowUi)
        self.actionNext.setObjectName(u"actionNext")
        self.actionPrevious_Track = QAction(MainWindowUi)
        self.actionPrevious_Track.setObjectName(u"actionPrevious_Track")
        self.actionDevice = QAction(MainWindowUi)
        self.actionDevice.setObjectName(u"actionDevice")
        self.actionStereo = QAction(MainWindowUi)
        self.actionStereo.setObjectName(u"actionStereo")
        self.actionIncrease_Volume = QAction(MainWindowUi)
        self.actionIncrease_Volume.setObjectName(u"actionIncrease_Volume")
        self.actionDecrease_Volume = QAction(MainWindowUi)
        self.actionDecrease_Volume.setObjectName(u"actionDecrease_Volume")
        self.actionMute = QAction(MainWindowUi)
        self.actionMute.setObjectName(u"actionMute")
        self.actionHelp = QAction(MainWindowUi)
        self.actionHelp.setObjectName(u"actionHelp")
        self.actionAbout = QAction(MainWindowUi)
        self.actionAbout.setObjectName(u"actionAbout")
        self.actionJump_to_Specific_Time_2 = QAction(MainWindowUi)
        self.actionJump_to_Specific_Time_2.setObjectName(u"actionJump_to_Specific_Time_2")
        self.actionNormal_1x_2 = QAction(MainWindowUi)
        self.actionNormal_1x_2.setObjectName(u"actionNormal_1x_2")
        self.actionFaster_2 = QAction(MainWindowUi)
        self.actionFaster_2.setObjectName(u"actionFaster_2")
        self.actionSlower_2 = QAction(MainWindowUi)
        self.actionSlower_2.setObjectName(u"actionSlower_2")
        self.centralwidget = QWidget(MainWindowUi)
        self.centralwidget.setObjectName(u"centralwidget")
        self.verticalLayout_2 = QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.splitter = QSplitter(self.centralwidget)
        self.splitter.setObjectName(u"splitter")
        self.splitter.setOrientation(Qt.Horizontal)
        self.frame_3 = QFrame(self.splitter)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setFrameShape(QFrame.Box)
        self.frame_3.setFrameShadow(QFrame.Plain)
        self.verticalLayout = QVBoxLayout(self.frame_3)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.categoryTabWidget = QTabWidget(self.frame_3)
        self.categoryTabWidget.setObjectName(u"categoryTabWidget")
        self.categoryTabWidget.setTabPosition(QTabWidget.North)
        self.categoryTabWidget.setTabShape(QTabWidget.Triangular)
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.categoryTabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.categoryTabWidget.addTab(self.tab_2, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.categoryTabWidget.addTab(self.tab_3, "")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.categoryTabWidget.addTab(self.tab_4, "")
        self.tab_5 = QWidget()
        self.tab_5.setObjectName(u"tab_5")
        self.categoryTabWidget.addTab(self.tab_5, "")

        self.verticalLayout.addWidget(self.categoryTabWidget)

        self.splitter.addWidget(self.frame_3)
        self.frame = QFrame(self.splitter)
        self.frame.setObjectName(u"frame")
        self.frame.setFrameShape(QFrame.Box)
        self.frame.setFrameShadow(QFrame.Plain)
        self.verticalLayout_4 = QVBoxLayout(self.frame)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.widget_2 = QWidget(self.frame)
        self.widget_2.setObjectName(u"widget_2")

        self.verticalLayout_4.addWidget(self.widget_2)

        self.splitter.addWidget(self.frame)

        self.verticalLayout_2.addWidget(self.splitter)

        self.frame_2 = QFrame(self.centralwidget)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setFrameShape(QFrame.Box)
        self.frame_2.setFrameShadow(QFrame.Plain)
        self.verticalLayout_3 = QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.widget = MediaPlayerWidget(self.frame_2)
        self.widget.setObjectName(u"widget")

        self.verticalLayout_3.addWidget(self.widget)


        self.verticalLayout_2.addWidget(self.frame_2)

        self.verticalLayout_2.setStretch(0, 1)
        MainWindowUi.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindowUi)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 920, 22))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuPlayback = QMenu(self.menubar)
        self.menuPlayback.setObjectName(u"menuPlayback")
        self.menuSpeed = QMenu(self.menuPlayback)
        self.menuSpeed.setObjectName(u"menuSpeed")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        MainWindowUi.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindowUi)
        self.statusbar.setObjectName(u"statusbar")
        MainWindowUi.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuPlayback.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menuFile.addAction(self.actionAddMusic)
        self.menuFile.addAction(self.actionAddDirectory)
        self.menuFile.addAction(self.actionNewPlaylist)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionImportDatabase)
        self.menuFile.addAction(self.actionExportDatabase)
        self.menuFile.addAction(self.actionImportPlaylist)
        self.menuFile.addAction(self.actionExportPlaylist)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSettings)
        self.menuPlayback.addAction(self.menuSpeed.menuAction())
        self.menuPlayback.addSeparator()
        self.menuPlayback.addAction(self.actionPlay_Pause)
        self.menuPlayback.addAction(self.actionStop)
        self.menuPlayback.addAction(self.actionNext)
        self.menuPlayback.addAction(self.actionPrevious_Track)
        self.menuPlayback.addSeparator()
        self.menuPlayback.addAction(self.actionJump_Forward)
        self.menuPlayback.addAction(self.actionFump_Backward)
        self.menuPlayback.addAction(self.actionJump_to_Specific_Time_2)
        self.menuPlayback.addSeparator()
        self.menuPlayback.addAction(self.actionIncrease_Volume)
        self.menuPlayback.addAction(self.actionDecrease_Volume)
        self.menuPlayback.addAction(self.actionMute)
        self.menuSpeed.addAction(self.actionNormal_1x_2)
        self.menuSpeed.addAction(self.actionFaster_2)
        self.menuSpeed.addAction(self.actionSlower_2)
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addAction(self.actionAbout)

        self.retranslateUi(MainWindowUi)

        self.categoryTabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindowUi)
    # setupUi

    def retranslateUi(self, MainWindowUi):
        MainWindowUi.setWindowTitle(QCoreApplication.translate("MainWindowUi", u"Tone Box", None))
        self.actionAddMusic.setText(QCoreApplication.translate("MainWindowUi", u"Add Music(s)", None))
        self.actionNewPlaylist.setText(QCoreApplication.translate("MainWindowUi", u"New Playlist", None))
        self.actionImportDatabase.setText(QCoreApplication.translate("MainWindowUi", u"Import Database", None))
        self.actionExportDatabase.setText(QCoreApplication.translate("MainWindowUi", u"Export Database", None))
        self.actionSettings.setText(QCoreApplication.translate("MainWindowUi", u"Settings", None))
        self.actionExportPlaylist.setText(QCoreApplication.translate("MainWindowUi", u"Export Playlist", None))
        self.actionAddDirectory.setText(QCoreApplication.translate("MainWindowUi", u"Add Directory", None))
        self.actionImportPlaylist.setText(QCoreApplication.translate("MainWindowUi", u"Import Playlist", None))
        self.actionNormal_1x.setText(QCoreApplication.translate("MainWindowUi", u"Normal (1x)", None))
        self.actionFaster.setText(QCoreApplication.translate("MainWindowUi", u"Faster (+0.1x)", None))
        self.actionSlower.setText(QCoreApplication.translate("MainWindowUi", u"Slower (-0.1x)", None))
        self.actionMush_Faster.setText(QCoreApplication.translate("MainWindowUi", u"Much Faster (+0.3x)", None))
        self.actionMuch_Slower.setText(QCoreApplication.translate("MainWindowUi", u"Much Slower (-0.3x)", None))
        self.actionJump_Forward.setText(QCoreApplication.translate("MainWindowUi", u"Jump Forward", None))
        self.actionFump_Backward.setText(QCoreApplication.translate("MainWindowUi", u"Jump Backward", None))
        self.actionJump_to_Specific_Time.setText(QCoreApplication.translate("MainWindowUi", u"Jump to Specific Time", None))
        self.actionPlay_Pause.setText(QCoreApplication.translate("MainWindowUi", u"Play/Pause", None))
        self.actionStop.setText(QCoreApplication.translate("MainWindowUi", u"Stop", None))
        self.actionNext.setText(QCoreApplication.translate("MainWindowUi", u"Next Track", None))
        self.actionPrevious_Track.setText(QCoreApplication.translate("MainWindowUi", u"Previous Track", None))
        self.actionDevice.setText(QCoreApplication.translate("MainWindowUi", u"Audio Device", None))
        self.actionStereo.setText(QCoreApplication.translate("MainWindowUi", u"Stereo", None))
        self.actionIncrease_Volume.setText(QCoreApplication.translate("MainWindowUi", u"Increase Volume", None))
        self.actionDecrease_Volume.setText(QCoreApplication.translate("MainWindowUi", u"Decrease Volume", None))
        self.actionMute.setText(QCoreApplication.translate("MainWindowUi", u"Mute", None))
        self.actionHelp.setText(QCoreApplication.translate("MainWindowUi", u"Help", None))
        self.actionAbout.setText(QCoreApplication.translate("MainWindowUi", u"About", None))
        self.actionJump_to_Specific_Time_2.setText(QCoreApplication.translate("MainWindowUi", u"Jump to Specific Time", None))
        self.actionNormal_1x_2.setText(QCoreApplication.translate("MainWindowUi", u"Normal", None))
        self.actionFaster_2.setText(QCoreApplication.translate("MainWindowUi", u"Faster", None))
        self.actionSlower_2.setText(QCoreApplication.translate("MainWindowUi", u"Slower", None))
        self.categoryTabWidget.setTabText(self.categoryTabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindowUi", u"Library", None))
        self.categoryTabWidget.setTabText(self.categoryTabWidget.indexOf(self.tab_2), QCoreApplication.translate("MainWindowUi", u"Albums", None))
        self.categoryTabWidget.setTabText(self.categoryTabWidget.indexOf(self.tab_3), QCoreApplication.translate("MainWindowUi", u"Artists", None))
        self.categoryTabWidget.setTabText(self.categoryTabWidget.indexOf(self.tab_4), QCoreApplication.translate("MainWindowUi", u"Genres", None))
        self.categoryTabWidget.setTabText(self.categoryTabWidget.indexOf(self.tab_5), QCoreApplication.translate("MainWindowUi", u"Playlists", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindowUi", u"File", None))
        self.menuPlayback.setTitle(QCoreApplication.translate("MainWindowUi", u"Playback", None))
        self.menuSpeed.setTitle(QCoreApplication.translate("MainWindowUi", u"Speed", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindowUi", u"Help", None))
    # retranslateUi

